/*  5. Number Guessing Game
A program where the computer generates a random number and the user has to guess it.
The program provides hints if the guessed number is too high or too low.
Following things should be covered in the program.
1. Program will generate a random number between 1 to 100 and the user needs to
input a number which can be guessed by the program itself. Hint: user Random
class to generate random numbers.
2. Show users too high or too low messages based on the number the user had
entered.
3. Number between 1 to 100 is only valid (including 1 and 100), any value out of 1 to
100 needs to be considered invalid.
4. Program will keep asking to enter a guess number until the user has successfully
entered the guess number which was generated by the program.
5. Show a congratulation message with the number of attempts the user had taken to
successfully identify the number.
*/
import 'dart:io';
import 'dart:math';

void main() {
  final random = Random();
  int targetNumber = random.nextInt(100) + 1;

  int guess = 0;
  int attempts = 0;

  print('Welcome to the Number Guessing Game!');
  print('Guess the number between 1 and 100.');

  while (guess != targetNumber) {
    print('Enter your guess:');
    String? input = stdin.readLineSync();
    
    if (input == null) {
      print('Invalid input. Please enter a number.');
      continue;
    }
    
    guess = int.tryParse(input) ?? -1;

    if (guess < 1 || guess > 100) {
      print('Invalid input. Number should be between 1 and 100.');
      continue;
    }

    attempts++;
    if (guess < targetNumber) {
      print('Too low! Try again.');
    } else if (guess > targetNumber) {
      print('Too high! Try again.');
    }
  }

  print('Congratulations! You guessed the number $targetNumber.');
  print('It took you $attempts attempts to guess the correct number.');
}
